'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { useVehicle } from '../../context/VehicleContext';
import { InformationButton } from '../../components/InformationButton';
import { RecordHistory } from '../../components/RecordHistory';
import { appendHealthRecord } from '../../utils/healthRecords';
import { HearingAudio } from '../../utils/hearingAudio';
import { Ear,HEARING_CONFIG,FrequencyStaircase,ToneThreshold,DigitStaircase,seeded } from '../../utils/hearingProtocol';
const button='min-h-11 px-5 py-3 rounded-xl border border-sky-400/25 bg-slate-900 disabled:opacity-40';
// Display the frequency axis in ascending order; retain the test/repeat order.
const graphFrequencies=[250,500,1000,2000,4000,8000] as const;
type Phase='idle'|'prepare'|'tone'|'digits'|'paused'|'result';
type Trial={id:number;ear:Ear;catch:boolean;started:number;deadline:number;answered:boolean;open:boolean};
export default function HearingPage(){
 const {isParked}=useVehicle(),parked=useRef(isParked);parked.current=isParked;
 const [phase,setPhase]=useState<Phase>('idle'),phaseRef=useRef<Phase>('idle');phaseRef.current=phase;
 const [notice,setNotice]=useState(''),[channels,setChannels]=useState({left:false,right:false}),[headphones,setHeadphones]=useState(false),[consent,setConsent]=useState(false),[save,setSave]=useState(false),[busy,setBusy]=useState(false);
 const [played,setPlayed]=useState({left:false,right:false});
 const [thresholds,setThresholds]=useState<ToneThreshold[]>([]),[stage,setStage]=useState(''),[results,setResults]=useState<Record<string,any>|null>(null),[answer,setAnswer]=useState(''),[tripletIndex,setTripletIndex]=useState(0),[digitReady,setDigitReady]=useState(false);
 const instruction=useRef<HTMLAudioElement|undefined>(undefined);
 const focusOwner=useRef(''),scheduledTrials=useRef(0);
 const digitCanSubmit=useRef(false);
 const engine=useRef<HearingAudio|undefined>(undefined),epoch=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),trial=useRef<Trial|undefined>(undefined),frequency=useRef(new FrequencyStaircase()),toneResults=useRef<ToneThreshold[]>([]),toneIndex=useRef(0),catches=useRef({total:0,falsePositive:0}),sequence=useRef(0);
 const seed=useRef(0),random=useRef<()=>number>(()=>Math.random()),din=useRef(new DigitStaircase()),currentDigits=useRef<number[]>([]),repeated=useRef(false),bankAbort=useRef<AbortController|undefined>(undefined),focusTimer=useRef<ReturnType<typeof setInterval>|undefined>(undefined),sessionDevice=useRef(''),awaitingSchedule=useRef<()=>void>(()=>{});
 const clear=useCallback(()=>{instruction.current?.pause();instruction.current=undefined;epoch.current++;if(timer.current)clearTimeout(timer.current);engine.current?.stop();trial.current=undefined;bankAbort.current?.abort();digitCanSubmit.current=false;setDigitReady(false);setBusy(false);},[]);
 const release=useCallback(()=>{if(focusTimer.current)clearInterval(focusTimer.current);focusTimer.current=undefined;try{if(localStorage.getItem('attune_hearing_audio_owner')===focusOwner.current){localStorage.removeItem('attune_hearing_audio_focus');localStorage.removeItem('attune_hearing_audio_owner');window.dispatchEvent(new Event('attune-audio-focus'));}}catch{}},[]);
 const pause=useCallback((reason:string)=>{clear();release();setPhase('paused');setChannels({left:false,right:false});setPlayed({left:false,right:false});setNotice(reason);},[clear,release]);
 useEffect(()=>()=>{clear();release();engine.current?.close();engine.current=undefined;},[clear,release]);
 useEffect(()=>{if(!isParked&&phase!=='idle'&&phase!=='result')pause('Araç PARK durumunda olmalı; hazırlık yeniden doğrulanacak.');},[isParked,phase,pause]);
 useEffect(()=>{const changed=(event:StorageEvent)=>{if(event.key==='attune_hearing_audio_owner'&&event.newValue&&event.newValue!==focusOwner.current&&focusTimer.current)pause('Başka pencerede ses testi başladı; bu test durduruldu.');};window.addEventListener('storage',changed);return()=>window.removeEventListener('storage',changed);},[pause]);
 const claim=()=>{if(!focusOwner.current)focusOwner.current=crypto.randomUUID();if(focusTimer.current)clearInterval(focusTimer.current);const publish=()=>{localStorage.setItem('attune_hearing_audio_owner',focusOwner.current);localStorage.setItem('attune_hearing_audio_focus',String(Date.now()+5000));window.dispatchEvent(new Event('attune-audio-focus'));};publish();focusTimer.current=setInterval(publish,2000);document.querySelectorAll('audio,video').forEach(el=>{const media=el as HTMLMediaElement;if(!media.muted)media.pause();});speechSynthesis.cancel();};
 const prepare=async()=>{if(!consent||!isParked)return;clear();release();engine.current?.close();engine.current=new HearingAudio(pause);const run=epoch.current;try{await engine.current.resume();if(run!==epoch.current||!parked.current)return;claim();seed.current=crypto.getRandomValues(new Uint32Array(1))[0];random.current=seeded(seed.current);setChannels({left:false,right:false});setPlayed({left:false,right:false});setHeadphones(false);setPhase('prepare');setNotice('Stereo kulaklığı takın. Düşük, rahat cihaz sesini seçin; test boyunca değiştirmeyin. Kanalı yalnız doğru kulağınızda duyuyorsanız doğrulayın.');
  const devices=await navigator.mediaDevices.enumerateDevices();sessionDevice.current=devices.filter(d=>d.kind==='audiooutput').map(d=>d.deviceId).join('|');
 }catch{if(run===epoch.current)pause('Ses çıkışı açılamadı. Tarayıcı ses iznini kontrol edin.');}};
 const channel=async(ear:Ear)=>{if(busy||phase!=='prepare')return;const run=epoch.current;setBusy(true);setNotice(`${ear==='left'?'Sol':'Sağ'} kanal örneği. Yalnız aynı tarafta duyduğunuzu aşağıdaki seçenekle doğrulayın.`);try{await engine.current!.tone(1000,-40,1,ear);if(run===epoch.current)setPlayed(v=>({...v,[ear]:true}));}catch{if(run===epoch.current)pause('Kanal örneği kesildi.');}finally{if(run===epoch.current)setBusy(false);}};
 const resetRun=()=>{clear();toneResults.current=[];toneIndex.current=0;scheduledTrials.current=0;catches.current={total:0,falsePositive:0};setThresholds([]);setResults(null);frequency.current=new FrequencyStaircase();};
 const finishTones=()=>{clear();release();const repeat=toneResults.current.filter(t=>t.frequency===1000),inconsistency=repeat.some(t=>t.repeat&&repeat.some(base=>!base.repeat&&base.ear===t.ear&&base.value!==null&&t.value!==null&&Math.abs(base.value-t.value)>10));
  const value={type:'longitudinal_measurement',methodVersion:HEARING_CONFIG.version,unit:'dBFS-peak',value:toneResults.current.map(t=>({ear:t.ear,frequency:t.frequency,value:t.value,status:t.status,repeat:!!t.repeat})),region:'left-and-right-ear',evaluatedArea:null,localMap:null,modelVersion:null,modelHash:null,referenceId:null,uncertainty:['uncalibrated-hardware','user-confirmed-channels','environment-noise'],thresholds:toneResults.current,catchTrials:catches.current.total,catchFalsePositive:catches.current.falsePositive,repeatInconsistent:inconsistency,quality:catches.current.falsePositive||inconsistency?'unreliable':'technical-complete',deviceSession:sessionDevice.current,calibrationProfile:null,seed:seed.current,captureConditions:{contextSampleRate:engine.current?.context.sampleRate,systemVolume:'not-observable; user-maintained',headphones:'user-reported',channels:'user-confirmed'},limitationCode:'NO_HARDWARE_CALIBRATION'};
  engine.current?.close();engine.current=undefined;setResults(value);setPhase('result');setNotice('Bu cihazdaki dijital duyulabilirlik sonucu. Klinik işitme derecesi hesaplanmaz.');};
 const scheduleTone=()=>{
  if(!parked.current||!engine.current)return;const run=epoch.current,index=toneIndex.current,ear:Ear=index<7?'left':'right',hz=HEARING_CONFIG.frequencies[index%7];setStage(`${ear==='left'?'Sol':'Sağ'} kulak · ses ayarını koruyun`);
  const gap=HEARING_CONFIG.gapMin+random.current()*(HEARING_CONFIG.gapMax-HEARING_CONFIG.gapMin);
  timer.current=setTimeout(async()=>{
   if(run!==epoch.current||phaseRef.current!=='tone'||!parked.current)return;
   if(++scheduledTrials.current>45){toneResults.current.push({ear,frequency:hz,value:null,status:'max-trials',unit:'dBFS-peak',trials:frequency.current.trials,repeat:index%7===6});setThresholds([...toneResults.current]);toneIndex.current++;scheduledTrials.current=0;frequency.current=new FrequencyStaircase();if(toneIndex.current>=14){finishTones();return;}awaitingSchedule.current();return;}
   const silent=random.current()<HEARING_CONFIG.catchProbability,duration=HEARING_CONFIG.durationMin+random.current()*(HEARING_CONFIG.durationMax-HEARING_CONFIG.durationMin);
   const current:Trial={id:++sequence.current,ear,catch:silent,started:Infinity,deadline:Infinity,answered:false,open:false};trial.current=current;
   if(silent)catches.current.total++;
   const opened=()=>{if(run!==epoch.current||trial.current!==current)return;current.started=performance.now();current.deadline=current.started+(duration+HEARING_CONFIG.responseSeconds)*1000;current.open=true;
   timer.current=setTimeout(()=>{
    if(run!==epoch.current||trial.current!==current)return;current.open=false;trial.current=undefined;
    if(!silent){const outcome=frequency.current.response(current.answered);if(outcome){toneResults.current.push({ear,frequency:hz,...outcome,unit:'dBFS-peak',trials:frequency.current.trials,repeat:index%7===6});setThresholds([...toneResults.current]);toneIndex.current++;scheduledTrials.current=0;frequency.current=new FrequencyStaircase();if(toneIndex.current>=14){finishTones();return;}}}
    awaitingSchedule.current();
   },(duration+HEARING_CONFIG.responseSeconds)*1000);};
   try{if(silent)opened();else void engine.current!.tone(hz,frequency.current.level,duration,ear,opened).catch(()=>{if(run===epoch.current)pause('Ses kesildi; hazırlığı yeniden doğrulayın.');});}catch{pause('Ses sinyali hazırlanamadı.');return;}
  },gap*1000);
 };
 awaitingSchedule.current=scheduleTone;
 const heard=useCallback(()=>{const t=trial.current;if(phaseRef.current!=='tone'||!t?.open||t.answered||performance.now()<t.started||performance.now()>t.deadline)return;t.answered=true;if(t.catch)catches.current.falsePositive++;},[]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.code==='Space'&&phaseRef.current==='tone'){event.preventDefault();if(!event.repeat)heard();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[heard]);
 const startTones=()=>{if(!channels.left||!channels.right||!headphones||!isParked||busy)return;resetRun();claim();setPhase('tone');phaseRef.current='tone';setNotice('Bir ses duyarsanız Duydum veya Space. Duymadığınızda bekleyin. Ekran ses zamanını göstermez.');scheduleTone();};
 const playDigits=async(replay=false)=>{if(!engine.current||!parked.current)return;if(timer.current)clearTimeout(timer.current);const run=epoch.current;digitCanSubmit.current=false;setBusy(true);setDigitReady(false);setAnswer('');if(!replay){currentDigits.current=Array.from({length:3},()=>Math.floor(random.current()*10));repeated.current=false;}else repeated.current=true;
  try{const mixed=engine.current.triplet(currentDigits.current,din.current.snr,random.current);await engine.current.play(mixed.pcm,'both');if(run!==epoch.current)return;digitCanSubmit.current=true;setDigitReady(true);setNotice('Duyduğunuz üç sayıyı sırayla girin. Ses ayarını değiştirmeyin.');timer.current=setTimeout(()=>{if(run===epoch.current)pause('Yanıt bekleme süresi doldu. Yanıtsız deneme puanlanmadı; hazırlığı yeniden doğrulayın.');},60000);}catch{if(run===epoch.current)pause('Sayı oynatımı kesildi.');}finally{if(run===epoch.current)setBusy(false);}};
 const startDigits=async()=>{if(!channels.left||!channels.right||!headphones||!isParked||busy)return;clear();claim();setBusy(true);setNotice('Sabit Türkçe sayı bankası doğrulanıyor…');const run=epoch.current;bankAbort.current=new AbortController();try{await engine.current!.loadBank(bankAbort.current.signal);if(run!==epoch.current)return;din.current=new DigitStaircase();setResults(null);setTripletIndex(1);setPhase('digits');phaseRef.current='digits';await playDigits();}catch{if(run===epoch.current)pause('Sayı bankası yüklenemedi; başka ses kullanılmadı.');}};
 const submitDigits=async()=>{if(!digitCanSubmit.current||!digitReady||answer.length!==3||busy)return;digitCanSubmit.current=false;if(timer.current)clearTimeout(timer.current);setDigitReady(false);din.current.respond(currentDigits.current,Array.from(answer).map(Number),repeated.current);
  if(din.current.scored.length>=HEARING_CONFIG.dinTrials){const value={...din.current.result(),bankVersion:engine.current?.manifest?.version,bankManifest:engine.current?.manifest?.digits.map(d=>({digit:d.digit,sha256:d.sha256})),auditoryAcceptance:engine.current?.manifest?.auditoryAcceptance,seed:seed.current,deviceSession:sessionDevice.current,history:din.current.history,region:'binaural',evaluatedArea:null,localMap:null,modelVersion:null,modelHash:null,referenceId:null,uncertainty:['experimental-TTS-bank','uncalibrated-hardware','environment-noise'],captureConditions:{contextSampleRate:engine.current?.context.sampleRate,systemVolume:'not-observable; user-maintained',headphones:'user-reported',channels:'user-confirmed',speechRMSDefinition:HEARING_CONFIG.dinSpeechRMS},calibrationProfile:null};clear();release();engine.current?.close();engine.current=undefined;setResults(value);setPhase('result');setNotice('Deneysel sayı ayırt etme sonucu; klinik DIN normu uygulanmaz.');return;}
  setTripletIndex(din.current.scored.length+1);await playDigits();};
 const saveResult=async()=>{if(!save||!results||!isParked)return;try{await appendHealthRecord('hearing',{id:crypto.randomUUID(),timestamp:new Date().toISOString(),...results,summaryText:results.thresholds?'Saf ses · dBFS peak · donanım kalibrasyonu yok':'Türkçe sayı ayırt etme · deneysel TTS bankası'}, {},()=>parked.current&&save);setNotice('Sayısal sonuç yerel geçmişe kaydedildi.');}catch(error){setNotice((error as Error).message);}};
 return <div className="space-y-6 max-w-5xl mx-auto" data-hearing-page><div className="flex items-center gap-3"><h1 className="text-2xl font-bold">İşitme Sağlığı</h1><InformationButton title="Bu cihazdaki duyulabilirlik"><p>Stereo kulaklık ve kullanıcı kanal doğrulaması gerekir. Tarayıcı kulaklığın takıldığını veya işletim sistemi sesini doğrulayamaz. Sonuçlar dBFS peak veya bu sayı bankasında dB SNR birimindedir; dB HL/SPL, klinik odyogram veya işitme kaybı değildir. Ahmet sayı bankasının işitsel kabulü bekleniyor; deneysel bankadır. Mikrofon açılmaz. Ses rahatsız ederse Durdur. Ham ses kaydedilmez; yalnız izin verirseniz sayısal sonuç bu tarayıcıda saklanır.</p></InformationButton></div>
  <section className="rounded-2xl border border-white/10 bg-cockpit-surface p-5 md:p-7 space-y-5">
   <p role="status" className="text-slate-300">{notice||'Sessiz ortamda stereo kulaklıkla iki ayrı dijital ön değerlendirme.'}</p>
   {(phase==='idle'||phase==='paused')&&<><button className={button} disabled={!isParked} onClick={()=>{instruction.current?.pause();instruction.current=new Audio('/audio/hearing-bank/hearing-prepare.wav');void instruction.current.play().catch(()=>setNotice('Yönerge sesi açılamadı; yazılı yönergeyi izleyin.'));}}>Yönergeyi dinle</button><label className="flex gap-3"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Yerel ses testi işlemini başlatmayı kabul ediyorum.</label><button className={button} disabled={!consent||!isParked} onClick={prepare}>Ses hazırlığını başlat</button></>}
   {phase==='prepare'&&<><label className="flex gap-3"><input type="checkbox" checked={headphones} onChange={e=>setHeadphones(e.target.checked)}/>Stereo kulaklık kullanıyorum; mono/speaker kullanmıyorum.</label><div className="grid sm:grid-cols-2 gap-4">{(['left','right'] as Ear[]).map(ear=><div key={ear} className="border border-white/10 p-4 rounded-xl space-y-3"><button className={button} disabled={busy} onClick={()=>channel(ear)}>{ear==='left'?'Sol':'Sağ'} kanalı dinle</button><label className="flex gap-3"><input type="checkbox" checked={channels[ear]} disabled={!played[ear]||busy} onChange={e=>setChannels(v=>({...v,[ear]:e.target.checked}))}/>{ear==='left'?'Yalnız sol':'Yalnız sağ'} kulağımda duydum.</label></div>)}</div><div className="flex gap-3 flex-wrap"><button className={button} disabled={busy||!headphones||!channels.left||!channels.right} onClick={startTones}>Saf ses testi</button><button className={button} disabled={busy||!headphones||!channels.left||!channels.right} onClick={startDigits}>Gürültüde Türkçe sayılar</button></div></>}
   {phase==='tone'&&<div className="min-h-44 flex flex-col items-center justify-center gap-5"><p>{stage}</p><button className={button+' text-xl w-full max-w-sm'} onClick={heard}>Duydum · Space</button></div>}
   {phase==='digits'&&<div className="space-y-4"><p>Üçlü {tripletIndex} / {HEARING_CONFIG.dinTrials} · Ses düzeyini koruyun</p><label className="block">Duyduğunuz üç sayı<input aria-label="Üç sayı yanıtı" inputMode="numeric" className="block mt-2 bg-black/30 rounded-xl border border-white/20 p-4 text-3xl tracking-widest w-full" value={answer} disabled={!digitReady} maxLength={3} onChange={e=>setAnswer(e.target.value.replace(/\D/g,'').slice(0,3))} onKeyDown={e=>{if(e.key==='Enter')void submitDigits();}}/></label><div className="grid grid-cols-5 gap-2">{Array.from({length:10},(_,i)=><button key={i} className={button} disabled={!digitReady||answer.length>=3} onClick={()=>setAnswer(v=>(v+i).slice(0,3))}>{i}</button>)}</div><div className="flex gap-3 flex-wrap"><button className={button} disabled={!digitReady} onClick={()=>setAnswer(v=>v.slice(0,-1))}>Son sayıyı sil</button><button className={button} disabled={!digitReady||answer.length!==3} onClick={submitDigits}>Yanıtı gönder</button><button className={button} disabled={!digitReady} onClick={()=>playDigits(true)}>Tekrar · skor dışı</button></div></div>}
   {phase==='result'&&results&&<div className="space-y-4" data-hearing-result>{results.thresholds?<><p>Bu cihazda duyulabilirlik · dBFS peak</p><svg viewBox="0 0 600 240" role="img" aria-label="Sol daire, sağ çarpı; yalnız bulunan dijital eşikler" className="w-full max-w-3xl bg-black/20 rounded-xl">{[-90,-75,-60,-45,-30].map((v,i)=><g key={v}><line x1="55" x2="570" y1={25+i*42} y2={25+i*42} stroke="#334155"/><text x="5" y={30+i*42} fontSize="12" fill="#94a3b8">{v}</text></g>)}{graphFrequencies.map((hz,i)=><text key={hz} x={75+i*85} y="225" fontSize="12" fill="#94a3b8">{hz} Hz</text>)}{thresholds.filter(t=>!t.repeat&&t.value!==null).map(t=>{const x=90+(graphFrequencies as readonly number[]).indexOf(t.frequency)*85,y=25+(t.value!+90)/60*168;return t.ear==='left'?<circle key={`${t.ear}-${t.frequency}`} cx={x} cy={y} r="6" fill="none" stroke="#38bdf8" strokeWidth="2"/>:<path key={`${t.ear}-${t.frequency}`} d={`M${x-6} ${y-6}L${x+6} ${y+6}M${x+6} ${y-6}L${x-6} ${y+6}`} stroke="#fda4af" strokeWidth="2"/>;})}</svg><div className="grid sm:grid-cols-2 gap-3">{thresholds.map((t,i)=><p key={i} className="text-sm">{t.ear==='left'?'Sol':'Sağ'} · {t.frequency} Hz{t.repeat?' tekrar':''}: {t.value===null?({'upper-limit':'Üst cihaz sınırında eşik bulunamadı','lower-limit':'Alt sınıra dayandı','max-trials':'Deneme sınırında yakınsamadı',threshold:'—'}[t.status]):`${t.value} dBFS peak`}</p>)}</div><p>Sessiz deneme yanıtı: {results.catchFalsePositive}/{results.catchTrials}. 1000 Hz tekrar: {results.repeatInconsistent?'Tutarsız':'Tutarsızlık saptanmadı; eksikler grafikte gösterilmez'}.</p></>:<><p>Doğru sayı: {Math.round((results.digitAccuracy||0)*100)}% · Tam üçlü: {Math.round((results.tripletAccuracy||0)*100)}% · {results.validTrials} geçerli deneme.</p><p>{results.value===null?'Kararlı SNR eşiği çıkarılamadı.':`Bu bankada eşik: ${Math.round(results.value)} dB SNR`}</p><p>Tekrar edilen skor dışı deneme: {results.repeated}.</p></>}<label className="flex gap-3"><input type="checkbox" checked={save} onChange={e=>setSave(e.target.checked)}/>Sayısal sonucu bu tarayıcıdaki geçmişe kaydet.</label><div className="flex gap-3 flex-wrap"><button className={button} disabled={!save||!isParked} onClick={saveResult}>Sonucu kaydet</button><button className={button} onClick={()=>{setResults(null);setThresholds([]);setPhase('idle');}}>Yeni test</button></div></div>}
   {!['idle','result'].includes(phase)&&<button className={button+' border-rose-400/50 text-rose-200'} onClick={()=>pause('Test durduruldu. Geçici sesler kapatıldı; hazırlık yeniden doğrulanacak.')}>Durdur</button>}
  </section><RecordHistory category="hearing" parked={isParked}/>
 </div>;
}
