'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useVehicle} from '../../context/VehicleContext';
import {InformationButton} from '../../components/InformationButton';
import {RecordHistory} from '../../components/RecordHistory';
import {SkinInference} from '../../utils/skinInference';
import {StablePreviewCrop,SourceMotion,cameraCrop,Crop} from '../../utils/cameraStability';
import {DentalCapture,DENTAL_POSES,DENTAL_GUIDANCE,assessDentalCapture,captureDental} from '../../utils/dentalCapture';
import {appendHealthRecord} from '../../utils/healthRecords';
import {isCameraAllowed} from '../../utils/attuneMode';
import type {FaceAlignment} from '../../utils/skinAnalyzer';
const button='min-h-11 px-5 py-3 rounded-xl border border-sky-400/25 bg-slate-900 disabled:opacity-40';
export default function DentalPage(){
 const {isParked}=useVehicle(),parked=useRef(isParked);parked.current=isParked;
 const [phase,setPhase]=useState<'ready'|'camera'|'analysis'|'result'|'error'>('ready'),[consent,setConsent]=useState(false),[save,setSave]=useState(false),[notice,setNotice]=useState(''),[index,setIndex]=useState(0),[progress,setProgress]=useState(0),[crop,setCrop]=useState<Crop>({x:0,y:0,width:1,height:1}),[ratio,setRatio]=useState(4/3),[result,setResult]=useState<any>(),[shown,setShown]=useState(0);
 const instruction=useRef<HTMLAudioElement|undefined>(undefined);
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|undefined>(undefined),inference=useRef<SkinInference|undefined>(undefined),epoch=useRef(0),abort=useRef<AbortController|undefined>(undefined),captures=useRef<DentalCapture[]>([]),display=useRef(new StablePreviewCrop()),motion=useRef(new SourceMotion()),validSince=useRef(0),lastFrame=useRef(-1),lastFresh=useRef(0),frameTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const stop=useCallback(()=>{instruction.current?.pause();instruction.current=undefined;epoch.current++;if(frameTimer.current)clearTimeout(frameTimer.current);stream.current?.getTracks().forEach(track=>track.stop());stream.current=undefined;inference.current?.close();inference.current=undefined;abort.current?.abort();},[]);
 const cancel=useCallback(()=>{stop();captures.current=[];setResult(undefined);setProgress(0);setPhase('ready');setNotice('Geçici fotoğraf ve sonuçlar temizlendi.');},[stop]);
 useEffect(()=>()=>{stop();captures.current=[];},[stop]);
 useEffect(()=>{const changed=()=>{if(!isCameraAllowed()){cancel();setNotice('Kamera izni geri çekildi.');}};window.addEventListener('attune-privacy',changed);window.addEventListener('storage',changed);return()=>{window.removeEventListener('attune-privacy',changed);window.removeEventListener('storage',changed);};},[cancel]);
 useEffect(()=>{if(!isParked&&phase!=='ready'){cancel();setNotice('Diş taraması yalnız PARK durumunda yapılır.');}},[isParked,phase,cancel]);
 const analyze=async(run:number)=>{
  setPhase('analysis');setNotice('Görünür diş yüzeyleri cihazda analiz ediliyor…');stream.current?.getTracks().forEach(track=>track.stop());inference.current?.close();abort.current=new AbortController();const timer=setTimeout(()=>abort.current?.abort(),30000);
  try{const response=await fetch('http://localhost:8000/api/local-health/dental',{method:'POST',headers:{'Content-Type':'application/json'},signal:abort.current.signal,body:JSON.stringify({processingConsent:consent,captures:captures.current})});if(!response.ok)throw Error('Yerel diş analizi tamamlanamadı.');const value=await response.json();if(run!==epoch.current||!parked.current)return;
   if(value.views.length!==captures.current.length||value.views.some((v:any,i:number)=>v.photoId!==captures.current[i].photoId))throw Error('Kaynak fotoğraf eşleşmesi doğrulanamadı.');
   setResult(value);setShown(0);setPhase('result');setNotice('Görünür alan ön değerlendirmesi. Çürük adayları tanı veya şiddet yüzdesi değildir.');
  }catch(error){if(run===epoch.current){setPhase('error');setNotice((error as Error).name==='AbortError'?'Analiz zamanında tamamlanamadı. Geçici fotoğrafları temizleyip yeniden başlayabilirsiniz.':(error as Error).message);}}finally{clearTimeout(timer);}
 };
 const start=async()=>{
  if(!consent||!isParked||!isCameraAllowed())return;stop();captures.current=[];setResult(undefined);setIndex(0);setProgress(0);setPhase('camera');setNotice('Kamera ve cihazdaki yüz modeli hazırlanıyor…');const run=epoch.current;
  try{const media=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1920},height:{ideal:1080}},audio:false});if(run!==epoch.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;inference.current=new SkinInference();await inference.current.initialize();if(run!==epoch.current)return;
   if(!video.current)throw Error('Kamera önizlemesi hazırlanamadı.');video.current.srcObject=media;await video.current.play();setRatio(video.current.videoWidth/video.current.videoHeight);const canvas=document.createElement('canvas'),analysis=document.createElement('canvas');validSince.current=0;lastFrame.current=-1;lastFresh.current=performance.now();display.current=new StablePreviewCrop();motion.current=new SourceMotion();
   const loop=async()=>{if(run!==epoch.current||!parked.current||!isCameraAllowed()||!video.current)return;const v=video.current,now=performance.now();
    if(v.readyState<2||v.currentTime===lastFrame.current){if(now-lastFresh.current>750){validSince.current=0;setProgress(0);setNotice('Kamera görüntüsü güncel değil.');}frameTimer.current=setTimeout(loop,100);return;}
    lastFrame.current=v.currentTime;lastFresh.current=now;canvas.width=v.videoWidth;canvas.height=v.videoHeight;const ctx=canvas.getContext('2d',{willReadFrequently:true})!;ctx.drawImage(v,0,0);
    const factor=Math.min(1,640/canvas.width);analysis.width=Math.round(canvas.width*factor);analysis.height=Math.round(canvas.height*factor);analysis.getContext('2d')!.drawImage(canvas,0,0,analysis.width,analysis.height);
    let a:FaceAlignment;try{a=await inference.current!.assessAlignment(analysis);}catch{if(run===epoch.current){setPhase('error');setNotice('Yüz modeli yanıt vermedi.');stop();}return;}if(run!==epoch.current)return;
    const pose=DENTAL_POSES[captures.current.length];setCrop(display.current.update(cameraCrop(a.landmarks),performance.now()));const quality=assessDentalCapture(ctx,a,pose),center=a.landmarks?.[1];const moving=center?motion.current.update(center.x,center.y,a.scaleRatio,performance.now()):true;
    if(quality.valid&&!moving){if(!validSince.current)validSince.current=performance.now();const held=performance.now()-validSince.current;setProgress(Math.min(100,Math.round(held/14)));setNotice(DENTAL_GUIDANCE[pose]+' Kısa süre sabit tutun.');
     if(held>=1400){const capture=await captureDental(canvas,a,pose);if(run!==epoch.current)return;captures.current.push(capture);validSince.current=0;setProgress(0);setIndex(captures.current.length);if(captures.current.length===4){await analyze(run);return;}setNotice(DENTAL_GUIDANCE[DENTAL_POSES[captures.current.length]]);}
    }else{validSince.current=0;setProgress(0);setNotice(moving?'Başınızı kısa süre sabit tutun.':quality.reasons[0]);}
    frameTimer.current=setTimeout(loop,160);
   };frameTimer.current=setTimeout(loop,100);
  }catch(error){if(run===epoch.current){stop();setPhase('error');setNotice((error as Error).message||'Kamera açılamadı.');}}
 };
 const saveResult=async()=>{if(!save||!result||!isParked)return;try{
  // No source pixels, thumbnails, local maps or photos enter persistent records.
  const measurements=result.views.map((view:any)=>({pose:view.pose,quality:view.quality,caries:view.caries,accumulation:view.accumulation,alignment:view.alignment}));
  await appendHealthRecord('dental',{id:crypto.randomUUID(),timestamp:new Date().toISOString(),methodVersion:result.methodVersion,measurements,summaryText:'Görünür diş yüzeyleri · çürük adayları, birikim ve dizilim vekilleri; klinik tanı değildir.'},{},()=>parked.current&&save);setNotice('Yalnız sayısal ölçüm ve aday koordinatları yerel geçmişe kaydedildi.');
 }catch(error){setNotice((error as Error).message);}};
 const view=result?.views[shown],photo=captures.current[shown];
 return <div className="space-y-6 max-w-6xl mx-auto" data-dental-page><div className="flex items-center gap-3"><h1 className="text-2xl font-bold">Diş Sağlığı</h1><InformationButton title="Görünür diş yüzeyleri"><p>Çürük adayları yerel, eğitilmiş YOLOX-s çıktılarıdır; confidence hastalık şiddeti değildir. Modelin ölçülen başarısı ve sınırları sonuç bilgisine eklenir. Diş arası, arka yüzey ve kök görünmüyorsa değerlendirilmez. Birikim görünümü; renk, doku ve diş eti sınırı adaylarının görünüm vekilidir. Leke, yiyecek ve dolgu ile karışabilir. Dizilim; güvenilir görünen konturların yön dağılımı, kamera düzlemindeki örtüşme ve sıra tutarlılığıdır. Gerçek üç boyutlu örtüşme, klinik maloklüzyon/FDI veya mm ölçümü değildir. Fotoğraflar bu oturumun belleğinde, cihaz içinde işlenir; üçüncü tarafa gönderilmez. Kayıt izni yalnız sayısal sonuç içindir.</p></InformationButton></div>
  <section className="border border-white/10 bg-cockpit-surface rounded-2xl p-5 md:p-7 space-y-5"><p role="status">{notice||'Ağzınıza cisim sokmadan, rahatça açıp doğal kapanışla görünür yüzeyleri tarayın.'}</p>
   {phase==='ready'&&<><button className={button} disabled={!isParked} onClick={()=>{instruction.current?.pause();instruction.current=new Audio('/audio/hearing-bank/dental-prepare.wav');void instruction.current.play().catch(()=>setNotice('Yönerge sesi açılamadı; yazılı yönergeyi izleyin.'));}}>Yönergeyi dinle</button><label className="flex gap-3"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Kamerayı açıp fotoğraflarımı yalnız bu cihazda geçici işlemeyi kabul ediyorum.</label><button className={button} disabled={!consent||!isParked||!isCameraAllowed()} onClick={start}>Kamerayı aç ve taramayı başlat</button></>}
   {phase==='camera'&&<div className="space-y-4"><p>{Math.min(index+1,4)} / 4 · {DENTAL_GUIDANCE[DENTAL_POSES[Math.min(index,3)]]}</p><div className="relative rounded-2xl overflow-hidden mx-auto w-full max-w-xl" style={{aspectRatio:ratio*crop.width/crop.height}}><div className="absolute" style={{width:`${100/crop.width}%`,height:`${100/crop.height}%`,left:`${-100*crop.x/crop.width}%`,top:`${-100*crop.y/crop.height}%`}}><video ref={video} muted playsInline autoPlay className="w-full h-full object-fill" data-dental-live-video/></div></div><p>Kararlı çekim hazırlığı: {progress}%</p></div>}
   {phase==='analysis'&&<p className="animate-pulse">Yerel analiz sürüyor. İptal edebilirsiniz.</p>}
   {phase==='error'&&<p role="alert" className="text-amber-200">{notice}</p>}
   {phase==='result'&&view&&photo&&<div className="grid lg:grid-cols-2 gap-6 items-start" data-dental-result><div className="space-y-4"><svg viewBox={`0 0 ${photo.width} ${photo.height}`} role="img" aria-label="Gerçek diş fotoğrafı ve görünür adaylar" className="rounded-2xl w-full"><image href={photo.photo} width={photo.width} height={photo.height}/>{view.caries?.candidates?.map((c:any,i:number)=><rect key={i} x={c.bounds.x} y={c.bounds.y} width={c.bounds.width} height={c.bounds.height} fill="none" stroke="#fda4af" strokeWidth={photo.width/300}/>)}{view.accumulation?.quality==='valid'&&view.accumulation.candidates.map((c:any,i:number)=><path key={i} d={c.points.map((p:number[],j:number)=>`${j?'L':'M'}${p[0]} ${p[1]}`).join(' ')+'Z'} fill="#36e4f1" fillOpacity=".25" stroke="#36e4f1"/>)}{view.alignment?.contours?.map((c:any,i:number)=><path key={i} d={c.points.map((p:number[],j:number)=>`${j?'L':'M'}${p[0]} ${p[1]}`).join(' ')+'Z'} fill="none" stroke="#c4b5fd" strokeWidth={photo.width/600}/>)}</svg><div className="flex gap-3 justify-center"><button className={button} onClick={()=>setShown(v=>(v+3)%4)}>Önceki</button><span className="py-3">{shown+1} / 4</span><button className={button} onClick={()=>setShown(v=>(v+1)%4)}>Sonraki</button></div></div><div className="space-y-4"><h2 className="text-xl font-bold">Görünür yüzeyler · {photo.pose==='BITE'?'Doğal kapanış':photo.pose==='FRONT'?'Ön':photo.pose==='RIGHT'?'Anatomik sağ':'Anatomik sol'}</h2><div className="border border-white/10 rounded-2xl p-4"><h3>Çürük adayı</h3><p>{view.caries?.value===null||!view.caries?'Bu görüntü/model için sonuç üretilemedi.':`${view.caries.value} görünür aday`}</p>{view.caries?.candidates?.map((c:any,i:number)=><p key={i} className="text-sm text-slate-400">Aday {i+1} · veri etiketi {c.classCode} · confidence {Math.round(c.confidence*100)}% (şiddet değil)</p>)}<InformationButton title="Modelin ölçülen sınırları"><p>Yalnız bu modelin ayrılmış test çıktıları: {JSON.stringify(view.caries?.evaluation||{})}. Aday olmaması çürük yok anlamına gelmez. Ağız içi veri ile araç kamerası farklı çekim koşullarıdır.</p></InformationButton></div><div className="border border-white/10 rounded-2xl p-4"><h3>Birikim görünümü</h3><p>{view.accumulation?.value===null||!view.accumulation?'Yeterli tutarlı sınır görünümü yok.':`${Math.round(view.accumulation.value)}% görünür sınır alanında aday`}</p></div><div className="border border-white/10 rounded-2xl p-4"><h3>Görünür ön diş dizilimi</h3>{view.alignment?.rows?Object.entries(view.alignment.rows).map(([which,v]:[string,any])=><p key={which}>{which==='upper'?'Üst':'Alt'} sıra: {v.value===null?'Konturlar güvenilir ayrılamadı.':`${Math.round(v.value)}° yön dağılımı · ${v.contourCount} kontur`}</p>):<p>Doğal kapanış fotoğrafında kontur hesabı gösterilir.</p>}</div></div></div>}
   {phase==='result'&&<><label className="flex gap-3"><input type="checkbox" checked={save} onChange={e=>setSave(e.target.checked)}/>Sayısal sonucu yerel geçmişime kaydet.</label><div className="flex flex-wrap gap-3"><button className={button} disabled={!save||!isParked} onClick={saveResult}>Sonucu kaydet</button><Link className={button} href="/care?specialty=Di%C5%9F%20Hekimli%C4%9Fi&from=DENTAL">Diş hekimi seçenekleri</Link></div></>}
   {phase!=='ready'&&<button className={button} onClick={cancel}>{phase==='result'?'Geçici görüntüleri temizle':'İptal et'}</button>}
  </section><RecordHistory category="dental" parked={isParked}/>
 </div>;
}
